### ISSUE TITLE
more GX01

### ISSUE THREAD

**Issue by xtexChooser** [ZauberViolino/Gongxiang01#1]
Backrooms wiki 低质量文章、滥用投票系统、广告，封禁
<https://backrooms.fandom.com/wiki/User:Gongxiang01>

Googology wiki 虚假信息和忽略讨论页警告，封禁
<https://googology.fandom.com/wiki/User:Gongxiang01>

Antimony Wiki 滥用投票系统、插入垃圾内容和广告、伪造管理员签名，封禁
<https://antimony.fandom.com/zh/wiki/User:Gongxiang01>

Darkrooms Wiki 滥用投票系统、创建人身攻击页面、骚扰社区成员、破坏条目，封禁
<https://darkrooms.fandom.com/zh/wiki/User:Gongxiang01>

Fandom全域封禁

MCBBS 滥用举报系统和使用虚拟手机号注册账号，封禁
<https://mcbbs.wiki/wiki/%E5%85%B6%E4%BB%96%E6%B0%B8%E4%B9%85%E5%B0%81%E7%A6%81%E7%94%A8%E6%88%B7/gongxiang01>

MCBBS Wiki 破坏页面和人身攻击，封禁
<https://mcbbs.wiki/index.php?title=%E7%89%B9%E6%AE%8A%3A%E7%94%A8%E6%88%B7%E8%B4%A1%E7%8C%AE&target=Gongxiang01&namespace=all&tagfilter=&start=&end=>

中文维基百科，长期破坏、滥用警告、多次编辑战，永久封禁，随后IP被全域封禁
<https://zh.wikipedia.org/wiki/Wikipedia:%E5%BD%93%E5%89%8D%E7%9A%84%E7%A0%B4%E5%9D%8F/%E5%AD%98%E6%A1%A3/2024%E5%B9%B45%E6%9C%88#Gongxiang01>

中文Minecraft Wiki，破坏，故意绕过滥用过滤器，封禁
<https://zh.minecraft.wiki/w/User:Gongxiang01>
被中文WP封禁后回到中文MCW持续破坏，直至前几天，中文MCW为之创建了滥用过滤器68,专杀之

Miraheze Meta Wiki，破坏页面、发布无意义留言、持续忽略警告、反复重开wiki创建请求、攻击志愿者，封禁
<https://meta.miraheze.org/wiki/Special:Contributions/Gongxiang01>

MineBBS，针对异见者滥用举报系统、反复创建离题贴子、引发骂战、傀儡行为，封禁
<https://www.minebbs.com/threads/oier.22115/#post-140631>

mediawiki.org、translatewiki.net破坏本地化文本，但还没到封禁标准

我上个月在zhWP盯着GX的WMF全域贡献看了一整个周末啊（（（（

Wikidot上面还有全域封禁，虽然没公开看不到封禁记录，但是<http://translate.wikidot.com/y:cn/comments/show#post-6484982>

**Comment by ZauberViolino** [comment]
#2 应该都补上了
