### ISSUE TITLE
很高兴看见有这个仓库

### ISSUE THREAD

**Issue by cmd1152** [ZauberViolino/Gongxiang01#11]
note.ms/0 之前的内容是我写的，然后呢现在我迁移到了 cmd1152.github.io/googol （这个是新站，原内容见 cmd1152.github./googol_old）
你们也可以直接拿去用，反正让更多人知道Googol的恶行就可以！

~~因为没找到能讨论的地方，所以塞在了issues，你们可以直接close掉~~

**Comment by ZauberViolino** [comment]
收到，感觉风格不是很像不好整合，先开着有空看看

**Comment by ZauberViolino** [comment]
先加到resources/reports.md里了，感谢您的整理

**Comment by cmd1152** [comment]
> 收到，感觉风格不是很像不好整合，先开着有空看看

雀氏，我直接写了个页面

**Comment by GoogolOwO** [comment]
关于 @cmd1152 有权限关闭的那些事

**Comment by xtexChooser** [comment]
有权限关闭怎么了

**Comment by cmd1152** [comment]
> 关于 @cmd1152 有权限关闭的那些事

我自己的issues我自己还不能关闭是吧
