### ISSUE TITLE
虚假信息

### ISSUE THREAD

**Issue by GoogolOwO** [ZauberViolino/Gongxiang01#15]
您好，您的内容存在虚假信息，希望您能够尽快删除，感谢您的配合：
- Googol不是Gongxiang01，对于Googol相关的信息请删除或特别声明不是Gongxiang01所为。
- 一些明显无关的用户被说成Gongxiang01所作，事实正确，但是不是Googol所作。
希望立即删除，谢谢。

**Comment by ZauberViolino** [comment]
Closed as not intended.

**Comment by GoogolOwO** [comment]
未完成。

~~由于您的行为，我们已经举报您的存储库~~

**Comment by GoogolOwO** [comment]
请以 Close as not planned 关闭，谢谢配合。

**Comment by PumpkinXD** [comment]
> 未完成。
> 
> ~~由于您的行为，我们已经举报您的存储库~~


哦，gx01不反思一下怎么各wiki的用户/编者/管理员怎么看你都和看过街老鼠一样人人喊打呢
