### ISSUE TITLE
补充材料

### ISSUE THREAD

**Issue by mikumiku-qwq** [ZauberViolino/Gongxiang01#16]
Googol曾经还有一个叫googologygithub的帐号，后因为骚扰他人被封禁。

Github支持联系记录：
https://github.com/user-attachments/files/16048069/googol.pdf

Github issue记录：
https://github.com/user-attachments/files/16048064/googologygithub.pdf

**Comment by ZauberViolino** [comment]
[b9d496b](https://github.com/ZauberViolino/Gongxiang01/commit/b9d496b44b2e865c44bdb79d231080c8c11d14da) 这样写？

**Comment by mikumiku-qwq** [comment]
可以（
