### ISSUE TITLE
感觉可以增加点monkeysites了

### ISSUE THREAD

**Issue by PumpkinXD** [ZauberViolino/Gongxiang01#20]
根据最近gx01在hcbbs的一些钓鱼发言来看
可以适当增加一些它所掌控的网页了

不过，可能需要增加关于js或者挂马的预警(它似乎在这些troll site上搞了一些盗号的东西)

_因为五天前割痔疮了我恐怕没办法对其站点进行统计总结_

**Comment by GoogolOwO** [comment]
gx01目前在 HcBBs 没有账号

**Comment by PumpkinXD** [comment]
我目前能找到的有这两个(注意：关闭js和xss或者使用虚拟机访问)：


```
https://doc-zhans.wikidot.com/


https://code-stolen.wikidot.com/start


```

**Comment by PumpkinXD** [comment]
> gx01目前在 HcBBs 没有账号

是指雷同的行为雷同的IP以及IP属地吗？<br>
你骗不了我的

**Comment by mikumiku-qwq** [comment]
> 我目前能找到的有这两个(注意：关闭js和xss或者使用虚拟机访问)：
> 
> 
> ```
> https://doc-zhans.wikidot.com/
> 
> 
> https://code-stolen.wikidot.com/start
> 
> 
> ```

xss应该不会影响电脑，退出帐号/隐私模式就行

**Comment by PumpkinXD** [comment]
我在隔壁又发现一个
```
https://scp-wiki-cn.wikidot.com/system:join

```
![Screenshot_20240720-210439_Edge.jpg](https://github.com/user-attachments/assets/54522055-5758-41bd-bc04-0568d0760d69)

**Comment by xtexChooser** [comment]
?不是这是SCP中文wiki不是googol的啊
设置暗号是为了让人申请前仔细阅读规则。

**Comment by xtexChooser** [comment]
我用我的账户（为SCP中文wiki成员，可访问讨论区）看了下讨论区的通告，GX也没变成职员/管理啊（（

**Comment by xtexChooser** [comment]
只能谴责一下这种乱发暗号的不当行为

**Comment by PumpkinXD** [comment]
> ?不是这是SCP中文wiki不是googol的啊
> 设置暗号是为了让人申请前仔细阅读规则。
> 

az 我应该是看岔了()

**Comment by PumpkinXD** [comment]
> 只能谴责一下这种乱发暗号的不当行为

还有，不清楚gx01是不是给scp wiki捣乱了
![Screenshot_20240721-143047_Edge.jpg](https://github.com/user-attachments/assets/f4d1f2ab-e63c-45e5-882c-8b1016c8770e)


或许需要查下编辑记录核实一下

**Comment by mikumiku-qwq** [comment]
我认为Googol应该去申请达尔文奖（关注点错误）

**Comment by xtexChooser** [comment]
抽象，我用crom搜索了下，没找到，主站最近记录我看了没有，SCP（CN）主站所有编辑都会有管理人员检查，没有先发沙盒投票的都会直接删除+警告，沙盒站和讨论区我看了下似乎没有（（

**Comment by GoogolOwO** [comment]
我都没有SCP网站成员资格

**Comment by PumpkinXD** [comment]
> 抽象，我用crom搜索了下，没找到，主站最近记录我看了没有，SCP（CN）主站所有编辑都会有管理人员检查，没有先发沙盒投票的都会直接删除+警告，沙盒站和讨论区我看了下似乎没有（（

可能是gx01用什么工具生成或者修改的

> 我都没有SCP网站成员资格
不妨碍在本仓的[相关记录](https://github.com/ZauberViolino/Gongxiang01/blob/main/site%2Fnodeloc.md)里面再多记录点

**Comment by xtexChooser** [comment]
（其实我觉得大概是预览
-- xtex

**Comment by PumpkinXD** [comment]
乐gx01破防了，给我这个号拉黑了

不过我也有github的小号，此外拉黑也不影响监视gx01的号（并举报）

不过这个issue我打算先关闭了，我身体也好差不多了

**Comment by PandaFiredoge** [comment]
> 我都没有SCP网站成员资格

Gongxiang01进盒！

**Comment by PandaFiredoge** [comment]
> > 抽象，我用crom搜索了下，没找到，主站最近记录我看了没有，SCP（CN）主站所有编辑都会有管理人员检查，没有先发沙盒投票的都会直接删除+警告，沙盒站和讨论区我看了下似乎没有（（
> 
> 可能是gx01用什么工具生成或者修改的
> 
> > 我都没有SCP网站成员资格
> 
> 不妨碍在本仓的[相关记录](https://github.com/ZauberViolino/Gongxiang01/blob/main/site%2Fnodeloc.md)里面再多记录点

可能是拿F12改的

**Comment by PandaFiredoge** [comment]
> gx01目前在 HcBBs 没有账号

![image](https://github.com/user-attachments/assets/d2a3d889-92ec-458b-bdf4-afa57dea062a)
