### ISSUE TITLE
对了 miraheze感觉也可以加点相关信息了

### ISSUE THREAD

**Issue by PumpkinXD** [ZauberViolino/Gongxiang01#24]
根据绿毛羊(即sheep-realm)前几天在牢坛wiki群和hcbbs所提，gx01近期仍然不死心在miraheze上创建小号搞事(甚至创下了9min的封禁时间记录)

或许可以有人汇总一下
(绿毛羊本人其实想fork本仓但他怕gx01去他GitHub账户那边找事；我则是仍然没有完全康复不能久坐且对gx01在miraheze上的事迹了解不多也没办法汇总)

**Comment by xtexChooser** [comment]
如果怕fork仓库有事，可以在QQ之类的平台给我发patch或者git diff，或者内容，sheep-realm知道在哪里可以找到我的（应该（

**Comment by xtexChooser** [comment]
可以给下MH的小号用户名吗（

**Comment by PumpkinXD** [comment]
> 可以给下MH的小号用户名吗（

https://netcut.cn/p/046e2c1a23ffc727

这里是绿毛羊汇总的，有一些已记录的也有没记录的(在下面)以及还有一些其他站的

**Comment by PumpkinXD** [comment]
此外，我听说gx01在freeflarum support forum的号炸了一个

我待会核实一下(

**Comment by PumpkinXD** [comment]
确认了，应该也是被扬了

具体时间点不太清楚，可能是早些时候

![Screenshot_20240717-225916_Edge.jpg](https://github.com/user-attachments/assets/7d608025-047c-46dc-b0b9-b6ad3fbe5b92)

**Comment by PumpkinXD** [comment]
身体好差不多了，有空我也搞搞汇总

先关闭issue了（gx01拉黑了我这个号，乐）
